import os
from pathlib import Path

from setuptools.command.build_py import build_py

BUILD_TARGET_ENV = "SGL_KERNEL_NPU_BUILD_TARGET"
DEFAULT_BUILD_TARGET = "Ascend910_9382"

_SOC_VERSION_ALIASES = {
    "910B": "Ascend910B1",
    "Ascend910B1": "Ascend910B1",
    "910C": "Ascend910_9382",
    "Ascend910_9382": "Ascend910_9382",
    "950": "Ascend950",
    "Ascend950": "Ascend950",
}


def normalize_soc_version(target: str) -> str:
    if target in _SOC_VERSION_ALIASES:
        return _SOC_VERSION_ALIASES[target]

    normalized = target.lower()
    if normalized.startswith(("ascend950pr_", "ascend950dt_")):
        return normalized

    supported = ", ".join(_SOC_VERSION_ALIASES)
    raise ValueError(
        f"Unsupported SOC_VERSION {target!r}; expected one of: {supported}, "
        "or a concrete ascend950pr_*/ascend950dt_* value"
    )


def get_gemma_provider(target: str) -> str:
    soc_version = normalize_soc_version(target)
    return (
        "aclnn"
        if soc_version == "Ascend950"
        or soc_version.startswith(("ascend950pr_", "ascend950dt_"))
        else "native"
    )


def write_build_target_config(build_lib: Path, target: str) -> None:
    soc_version = normalize_soc_version(target)
    config_path = Path(build_lib) / "sgl_kernel_npu" / "_build_target.py"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(
        "# Generated by the wheel build. Do not edit.\n"
        f'SOC_VERSION = "{soc_version}"\n'
        f'GEMMA_RMS_NORM_PROVIDER = "{get_gemma_provider(soc_version)}"\n',
        encoding="utf-8",
    )


def get_build_target() -> str:
    """Return the Ascend product selected for this wheel build."""
    return normalize_soc_version(os.environ.get(BUILD_TARGET_ENV, DEFAULT_BUILD_TARGET))


class TargetBuildPy(build_py):
    """Embed the selected Ascend target in the built wheel."""

    def run(self):
        super().run()
        write_build_target_config(Path(self.build_lib), get_build_target())
