name: PR Test (Ascend NPU)

on:
  pull_request:
    branches: [ main ]
    paths:
      - "python/**"
      - "csrc/**"
      - "test/**"
      - ".github/workflows/pr-test-npu.yml"
  workflow_dispatch:

concurrency:
  group: pr-test-npu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-low-latency:
    if: (github.repository == 'sgl-project/sgl-kernel-npu' || github.event_name == 'pull_request') &&
        github.event.pull_request.draft == false
    runs-on: linux-aarch64-a3-node0
    steps:
      - name: Clean git config
        run: git config --global --unset http.https://gh-proxy.test.osinfra.cn/.extraheader

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start CI container
        run: bash scripts/npu_ci_a3_start_container.sh

      - name: Run test
        timeout-minutes: 10
        run: |
          docker exec sglang_ci_a3 bash test/python/deepep/run_test.sh

  test-intranode:
    if: (github.repository == 'sgl-project/sgl-kernel-npu' || github.event_name == 'pull_request') &&
        github.event.pull_request.draft == false
    runs-on: linux-aarch64-a3-node0
    steps:
      - name: Clean git config
        run: git config --global --unset http.https://gh-proxy.test.osinfra.cn/.extraheader

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start CI container
        run: bash scripts/npu_ci_a3_start_container.sh

      - name: Run test
        timeout-minutes: 10
        run: |
          docker exec sglang_ci_a3 python3 test/python/test_intranode.py

  finish:
    if: always()
    needs:
      - test-low-latency
      - test-intranode
    runs-on: ubuntu-latest
    steps:
      - name: Check all dependent job statuses
        run: |
          results=(${{ join(needs.*.result, ' ') }})
          for result in "${results[@]}"; do
            if [ "$result" = "failure" ] || [ "$result" = "cancelled" ]; then
              echo "Job failed with result: $result"
              exit 1
            fi
          done
          echo "All jobs completed successfully"
          exit 0